<field:guojia itemname="国家" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="英国,美国,澳大利亚,日本,西班牙,荷兰,意大利,其它国家"  maxlength="250" page="">
</field:guojia>
<field:leixing itemname="类型" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="初中,高中,本科,硕士,其它"  maxlength="250" page="">
</field:leixing>
<field:feiyong itemname="费用" autofield="1" notsend="0" type="radio" isnull="true" islist="0" default="0-5万,5-10万,10-15万,15-20万,20-25万,25-30万,30万以上"  maxlength="250" page="">
</field:feiyong>
<field:wangzhi itemname="学校网址" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:wangzhi>
<field:dizhi itemname="学校地址" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dizhi>
<field:body itemname="详细介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">	
</field:body>