<?php
$z[0]=Array("fenlei","\r\n",0,182);
$z[0][4]['itemname']="所属分类";
$z[0][4]['autofield']="1";
$z[0][4]['notsend']="0";
$z[0][4]['type']="radio";
$z[0][4]['isnull']="true";
$z[0][4]['islist']="0";
$z[0][4]['default']="初中,高中,本科,硕士";
$z[0][4]['maxlength']="250";
$z[0][4]['page']="";
$z[1]=Array("body","	\r\n",188,345);
$z[1][4]['itemname']="文章内容";
$z[1][4]['autofield']="0";
$z[1][4]['notsend']="0";
$z[1][4]['type']="htmltext";
$z[1][4]['isnull']="true";
$z[1][4]['islist']="1";
$z[1][4]['default']="";
$z[1][4]['maxlength']="";
$z[1][4]['page']="split";

?>