
<field:xingming itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xingming>

<field:dianhua itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dianhua>

<field:mail itemname="E-mail" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mail>

<field:xingbie itemname="性别" autofield="1" type="radio" isnull="true" default="男,女"  maxlength="250" page="">
</field:xingbie>

<field:leixing itemname="留学类型" autofield="1" type="radio" isnull="true" default="初中,高中,本科,硕士,其他"  maxlength="250" page="">
</field:leixing>

<field:guojia itemname="意向国家" autofield="1" type="checkbox" isnull="true" default="英国,美国,澳大利亚,日本,西班牙,荷兰,意大利,其他
"  maxlength="250" page="">
</field:guojia>



<field:shijian itemname="计划留学时间" autofield="1" type="radio" isnull="true" default="一个月内,两个月内,三个月内,半年内,一年内,两年内,两年后"  maxlength="250" page="">
</field:shijian>
