
    <m:item name='普通文章' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />
  <m:item name='院校' ischannel='1' link='content_list.php?channelid=6' linkadd='archives_add.php?channelid=6' channelid='6' rank='' target='main' />
  <m:item name='国家' ischannel='1' link='content_list.php?channelid=17' linkadd='archives_add.php?channelid=17' channelid='17' rank='' target='main' />
  <m:item name='新闻' ischannel='1' link='content_list.php?channelid=18' linkadd='article_add.php?channelid=18' channelid='18' rank='' target='main' />
  <m:item name='专家团队' ischannel='1' link='content_list.php?channelid=19' linkadd='article_add.php?channelid=19' channelid='19' rank='' target='main' />

  <m:item name='专题管理' ischannel='1' link='content_s_list.php' linkadd='spec_add.php' channelid='-1' rank='spec_New' target='main' />
