<?php
$z[0]=Array("global","",107,139);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("channel"," <a href=\"[field:typelink/]\">[field:typename/]</a> ",335,452);
$z[1][4]['row']="6";
$z[1][4]['type']="son";
$z[1][4]['typeid']="16";
$z[2]=Array("channel"," <a href=\"[field:typelink/]\">[field:typename/]</a> ",588,705);
$z[2][4]['row']="12";
$z[2][4]['type']="son";
$z[2][4]['typeid']="1";
$z[3]=Array("channel"," <a href=\"[field:typelink/]\">[field:typename/]</a> ",841,945);
$z[3][4]['row']="6";
$z[3][4]['type']="top";
$z[4]=Array("flink"," [field:link /] |  ",1489,1558);
$z[4][4]['row']="20";
$z[4][4]['type']="textall";
$z[5]=Array("global","",1933,1957);
$z[5][4]['name']="cfg_beian";
$z[6]=Array("global","",2231,2263);
$z[6][4]['name']="cfg_templets_skin";

?>