<?php
$z[0]=Array("channel","\r\n        <li><span class=\"\"></span><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n        ",202,383);
$z[0][4]['row']="6";
$z[0][4]['orderby']="typeid";
$z[0][4]['orderway']="asc";
$z[0][4]['type']="top";
$z[1]=Array("global","",701,733);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("channel"," <a href=\"[field:typelink/]\">[field:typename/]</a> ",1413,1530);
$z[2][4]['row']="15";
$z[2][4]['type']="son";
$z[2][4]['typeid']="1";
$z[3]=Array("channel"," <a href=\"[field:typelink/]\">[field:typename/]</a> ",1614,1730);
$z[3][4]['row']="5";
$z[3][4]['type']="son";
$z[3][4]['typeid']="5";
$z[4]=Array("channel"," <a href=\"[field:typelink/]\">[field:typename/]</a> ",1773,1889);
$z[4][4]['row']="7";
$z[4][4]['type']="son";
$z[4][4]['typeid']="1";
$z[5]=Array("channel"," <a href=\"[field:typelink/]\">[field:typename/]</a> ",1932,2049);
$z[5][4]['row']="15";
$z[5][4]['type']="son";
$z[5][4]['typeid']="15";
$z[6]=Array("channel"," <a href=\"[field:typelink/]\">[field:typename/]</a> ",2135,2252);
$z[6][4]['row']="15";
$z[6][4]['type']="son";
$z[6][4]['typeid']="16";

?>