<?php
$z[0]=Array("arclist","\r\n						                        <li><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></li>\r\n						   ",185,367);
$z[0][4]['row']="10";
$z[0][4]['titlelen']="30";
$z[0][4]['typeid']="1";
$z[1]=Array("global","",630,662);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",793,825);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",907,939);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1092,1113);
$z[4][4]['name']="cfg_qq";

?>