<?php
$z[0]=Array("arclist","\r\n					                    <li><span>[field:image/]</span><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></li>\r\n					   ",165,383);
$z[0][4]['row']="12";
$z[0][4]['typeid']="34";
$z[0][4]['imgwidth']="20";
$z[0][4]['imgheight']="20";
$z[1]=Array("arclist","\r\n					                    <li><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></li>\r\n					      ",616,796);
$z[1][4]['row']="10";
$z[1][4]['titlelen']="32";
$z[1][4]['typeid']="35";

?>