<?php
$z[0]=Array("arclist","\r\n						                        <li><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></li>\r\n						   ",193,376);
$z[0][4]['row']="10";
$z[0][4]['titlelen']="40";
$z[0][4]['typeid']="21";
$z[1]=Array("global","",634,666);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",797,829);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",911,943);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1096,1117);
$z[4][4]['name']="cfg_qq";

?>